- name: task level variables
  hosts: localhost
  connection: local
  vars: 
    Course: AWS with Devops
    Duration: 120 hrs
    Trainers: Shiva
  tasks:
    - name: print the course info
      vars:
        Course: Ansible
      ansible.builtin.debug:
         msg: "Course name is: {{ Course }} , Duration is: {{ Duration }} , Trainer is: {{Trainers}}"