- name: play level variables
  hosts: localhost
  connection: local
  vars: 
    Course: Devops with AWS
    Duration: 7HRS
    Trainer: Dev Guru
  tasks:
  - name: print course
    vars:
      Course: Ansible check
    ansible.builtin.debug:
      msg: "Course name is: {{ Course }}"