- name: play level variables
  hosts: localhost
  connection: local
  vars: #Play level Variables
  tasks:
  - name: print course
    vars: #Task level variables
      Course: Ansible check 
    ansible.builtin.debug:
      msg: "Course name is: {{ Course }}"