- name: varibles from files
  hosts: localhost
  connection: local
  vars_files: 
  - Course.yaml
  tasks: 
    - name: Ansible Course
      ansible.builtin.debug:
        msg: "Course name is: {{ Course }}"
