- name: datatypes
  hosts: local
  connection: local 
  vars: 
    Course: "Devops with AWS"
    Duration: 120
    is_live: true
    tools: #["Linux", "Shell", "Ansible"]
    -  "Linux"
    -  "Shell"
    -  "ansible"
  tasks:
  - name: print course info
    ansible.builtin.debug:
     msg: "Course name: {{Course}}, tools name is: {{tools}}"


#list: [] ['Devops', 'Linux']
#map: {} "{devops, linux}""