- name: usage of facts
  hosts: local 
  connection: local 
  become: yes 
  tasks: 
    - name: install nginx if redhat
      ansible.builtin.dnf:
        name: nginx
        state: latest
      when: ansibile_os_family == "RedHat"