- name: loops using packages
  hosts: local
  connection: local
  become: yes
  tasks:
   - name: Print names
     ansible.builtin.package:
      name: "{{ item }}"
      state: latest
     loop:
      - nginx
      - git
      - mysql
